services:
  db:
    image: 'postgres:latest'
    container_name: postgres_cinema
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres_cinema
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_cinema_data:/var/lib/postgresql/data/
    networks:
      - cinema_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.0.0.1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_cinema
    ports:
      - "3333:80"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres_cinema
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_cinema_data:/var/lib/pgadmin
    networks:
      - cinema_network

  web:
    restart: always
    build: .
    container_name: backend_cinema
    command: [ "/bin/bash", "/commands/run_web_server_dev.sh" ]
    env_file:
      - .env
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/usr/src/fastapi
      - WATCHFILES_FORCE_POLLING=true
      - POSTGRES_HOST=postgres_cinema
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/fastapi
    networks:
      - cinema_network

  migrator:
    build: .
    container_name: alembic_migrator_cinema
    command: ["/bin/bash", "/commands/run_migration.sh"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/fastapi
    env_file:
      - .env
    environment:
      - PYTHONPATH=/usr/src/fastapi
      - POSTGRES_HOST=postgres_cinema
    networks:
      - cinema_network

  redis:
    image: redis:latest
    container_name: redis_movie
    ports:
      - "6379:6379"
    networks:
      - cinema_network

  celery:
    build: .
    container_name: celery_cinema
    working_dir: /app
    command: [ "/bin/bash", "/commands/run_celery_worker.sh" ]
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - POSTGRES_HOST=postgres_cinema

    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - cinema_network

  celery-beat:
    build: .
    container_name: celery_beat
    working_dir: /app
    command: [ "/bin/bash", "/commands/run_celery_beat.sh" ]
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - POSTGRES_HOST=postgres_cinema

    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - celery
    networks:
      - cinema_network

volumes:
  postgres_cinema_data:
    driver: local
  pgadmin_cinema_data:
    driver: local

networks:
  cinema_network:
    driver: bridge